enum Sexe {
  F
  H
}

type GroupeParlementaire {
  Sigle: String! @unique @index
  NomComplet: String
  Couleur: String
  CouleurDetail: CouleurDetail
  URLImage: String
  Ordre: Int
  Actif: Boolean
  Deputes: [Depute!]! @relation
}

type CouleurDetail @embedded {
  HSL: HSLDetail
  RGB: RGBDetail
  HEX: String
}

type HSLDetail @embedded {
  Full: String
  H: Int
  S: Int
  L: Int
}

type RGBDetail @embedded {
  Full: String
  R: Int
  G: Int
  B: Int
}

type AncienMandat {
  AncienMandatComplet: String! @unique @index
  DateDeDebut: String
  DateDeFin: String
  Intitule: String
  Deputes: [Depute!]! @relation
}

type AutreMandat {
  AutreMandatComplet: String! @unique @index
  Localite: String
  Institution: String
  Intitule: String
  Deputes: [Depute!]! @relation
}

type Activite {
  DateDeDebut: String!
  DateDeFin: String!
  NumeroDeSemaine: Int!
  PresencesEnCommission: Int!
  PresenceEnHemicycle: Int!
  ParticipationsEnCommission: Int!
  ParticipationEnHemicycle: Int!
  Question: Int!
  Vacances: Int!
  Depute: Depute!
}

type Adresse {
  AdresseComplete: String! @unique @index
  Adresse: String!
  CodePostal: String
  Telephone: String
  Fax: String
  Deputes: [Depute!]! @relation
}

type Depute {
  # Attributes
  Slug: String! @unique @index
  Nom: String
  NomDeFamille: String
  Prenom: String
  DateDeNaissance: String
  LieuDeNaissance: String
  NumeroDepartement: String
  NomDepartement: String
  NumeroRegion: String
  NomRegion: String
  NomCirconscription: String
  NumeroCirconscription: Int
  DebutDuMandat: String
  RattachementFinancier: String
  Profession: String
  PlaceEnHemicycle: String
  URLAssembleeNationale: String
  IDAssembleeNationale: String
  URLNosdeputes: String
  URLNosdeputesAPI: String
  NombreMandats: Int!
  Twitter: String
  EstEnMandat: Boolean!
  Age: Int
  Sexe: Sexe
  URLPhotoAssembleeNationale: String
  URLPhotoAugora: String

  # Arrays
  SitesWeb: [String]!
  Emails: [String]!
  Collaborateurs: [String]!

  # Relations
  GroupeParlementaire: GroupeParlementaire!
  Activites: [Activite!]! @relation
  AdressesDetails: [Adresse!]! @relation
  AnciensMandats: [AncienMandat!]! @relation
  AutresMandats: [AutreMandat!]! @relation
}

type Query {
  Depute(Slug: String!): Depute!

  Deputes: [Depute!]!
  DeputesEnMandat(EstEnMandat: Boolean): [Depute!]!

  Adresses: [Adresse!]!

  GroupesParlementairesDetails: [GroupeParlementaire!]!
  GroupesParlementairesDetailsActifs(Actif: Boolean!): [GroupeParlementaire!]!
}
