enum GroupeSigle {
  GDR
  LFI
  LR
  LREM
  LT
  MODEM
  NI
  NG
  SOC
  UAI
}

enum Sexe {
  F
  H
}

type GroupeParlementaire {
  Sigle: String! @unique @index
  NomComplet: String
  Couleur: String
  URLImage: String
  Ordre: Int
  Deputes: [Depute!] @relation
}

type AncienMandat {
  AncienMandatComplet: String! @unique @index
  DateDeDebut: String
  DateDeFin: String
  Intitule: String
  Deputes: [Depute!] @relation
}

type AutreMandat {
  AutreMandatComplet: String! @unique @index
  Localite: String
  Institution: String
  Intitule: String
  Deputes: [Depute!] @relation
}

type Activite {
  DateDeDebut: String
  DateDeFin: String
  NumeroDeSemaine: Int
  PresencesEnCommission: Int
  PresenceEnHemicycle: Int
  ParticipationsEnCommission: Int
  ParticipationEnHemicycle: Int
  Question: Int
  Vacances: Int
  Depute: Depute!
}

type Adresse {
  AdresseComplete: String! @unique @index
  Adresse: String
  CodePostal: String
  Telephone: String
  Deputes: [Depute!] @relation
}

type Depute {
  # Attributes
  Slug: String! @unique @index
  Nom: String
  NomDeFamille: String
  Prenom: String
  DateDeNaissance: String
  LieuDeNaissance: String
  NumeroDepartement: String
  NomCirconscription: String
  NumeroCirconscription: Int
  DebutDuMandat: String
  parti_ratt_financier: String
  Profession: String
  PlaceEnHemicycle: String
  URLAssembleeNationnale: String
  IDAssembleeNationnale: String
  URLNosdeputes: String
  URLNosdeputesAPI: String
  NombreMandats: Int
  Twitter: String
  EstEnMandat: Boolean
  Age: Int
  SigleGroupePolitique: GroupeSigle @deprecated
  Sexe: Sexe

  # Arrays
  SitesWeb: [String]
  Emails: [String]
  Collaborateurs: [String]
  Adresses: [String] @deprecated

  # Relations
  GroupeParlementaire: GroupeParlementaire!
  Activites: [Activite] @relation
  AdressesDetails: [Adresse!] @relation
  AnciensMandats: [AncienMandat!] @relation
  AutresMandats: [AutreMandat!] @relation
}

type Query {
  Depute(Slug: String!): Depute!
  Deputes: [Depute!]
  DeputesEnMandat(EstEnMandat: Boolean): [Depute!]
  GroupeParlementaire(Sigle: String!): GroupeParlementaire
  GroupesParlementaires: [String!]
    @resolver(name: "GroupesParlementaires")
    @deprecated(reason: "Please use GroupesParlementairesDetails instead.")
  GroupesParlementairesDetails: [GroupeParlementaire!]
  Adresse(AdresseComplete: String!): Adresse!
  Adresses: [Adresse!]
}
