query GroupesParlementairesDetailsActifs {
  GroupesParlementairesDetailsActifs(Actif: true) {
    data {
      Sigle
      NomComplet
      Ordre
      Couleur
      Actif
      URLImage
    }
  }
}
